### ISSUE TITLE
Experiment Setup broken

### ISSUE THREAD

**Issue by jannikbach** [HazyResearch/spacetime#3]
Hey Everyone,

when I ran the experiments for the univariate ETTh1.csv everything worked properly and I also did some tests with my own data.

Oddly when I want to train multivariate data with `python main.py --dataset etth1 --features M --lag 336 --horizon 720 --embedding_config embedding/repeat --encoder_config encoder/default --decoder_config decoder/default --output_config output/default --n_blocks 1 --kernel_dim 64 --norm_order 1 --batch_size 50 --dropout 0.25 --lr 1e-3 --weight_decay 1e-4 --max_epochs 500 --early_stopping_epochs 20 --data_transform mean --loss informer_rmse --val_metric informer_rmse --criterion_weights 1 1 1 --seed 0 --no_wandb`  it breaks with the following error:

```
Traceback (most recent call last):
  File "/home/i53/student/j_bach/Documents/spacetime/main.py", line 178, in <module>
    main()
  File "/home/i53/student/j_bach/Documents/spacetime/main.py", line 141, in main
    model = train_model(model, optimizer, scheduler, dataloaders_by_split,
  File "/home/i53/student/j_bach/Documents/spacetime/train/train.py", line 61, in train_model
    _, metrics, y, hopefully_context = run_epoch(model, dataloaders_by_split, optimizer, scheduler,
  File "/home/i53/student/j_bach/Documents/spacetime/train/epoch.py", line 26, in run_epoch
    model, _metrics, y, x = shared_step(model, dataloader, optimizer, scheduler,
  File "/home/i53/student/j_bach/Documents/spacetime/train/step/informer.py", line 71, in shared_step
    y_pred, z_pred = model(u)
  File "/home/temp_store/j_bach/miniconda3/envs/spacetime/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/i53/student/j_bach/Documents/spacetime/model/network.py", line 96, in forward
    z = self.encoder(z)
  File "/home/temp_store/j_bach/miniconda3/envs/spacetime/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/i53/student/j_bach/Documents/spacetime/model/block.py", line 88, in forward
    return self.blocks(x)
  File "/home/temp_store/j_bach/miniconda3/envs/spacetime/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/temp_store/j_bach/miniconda3/envs/spacetime/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/temp_store/j_bach/miniconda3/envs/spacetime/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/i53/student/j_bach/Documents/spacetime/model/block.py", line 42, in forward
    y = self.mlp(y)
  File "/home/temp_store/j_bach/miniconda3/envs/spacetime/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/i53/student/j_bach/Documents/spacetime/model/mlp.py", line 114, in forward
    x = self.layers(x) + x
RuntimeError: The size of tensor a (128) must match the size of tensor b (896) at non-singleton dimension 2
```

Can anyone confirm they have the same problem or even better a fix? 

Best regards

**Comment by jannikbach** [comment]
Update: I saw in commit `01b99cc6` that for the multivariate forecasting new config files [`encoder/default_no_skip`, `mpl/default_no_skip`, `ssm/companion_no_skip`] where added. 

With ```python main.py --dataset etth1 --features M --lag 336 --horizon 720 --embedding_config embedding/repeat --encoder_config encoder/default_no_skip --decoder_config decoder/default --output_config output/default --n_blocks 1 --kernel_dim 64 --norm_order 1 --batch_size 50 --dropout 0.25 --lr 1e-3 --weight_decay 1e-4 --max_epochs 500 --early_stopping_epochs 20 --data_transform mean --loss informer_rmse --val_metric informer_rmse --criterion_weights 1 1 1 --seed 0 --no_wandb```

The model trains on multivariate data but I assume there are some architectural changes.

If this is the way the model is intended to be used on multivariate data I will close this issue.

**Comment by Sherlockuzi** [comment]
I'm having the same problem, how did you solve it?

**Comment by mzio** [comment]
Hi @jannikbach  @Sherlockuzi thanks for bringing this up! Really sorry for the late replies, just getting these notifications.

The scripts as-is were tested just for the Informer univariate forecasting tasks. 

Based on the error message + fix described:
```
  File "/home/i53/student/j_bach/Documents/spacetime/model/mlp.py", line 114, in forward
    x = self.layers(x) + x
RuntimeError: The size of tensor a (128) must match the size of tensor b (896) at non-singleton dimension 2
```
I think you want to change the `--output_config` or edit the `output_dim` variable in https://github.com/HazyResearch/spacetime/blob/main/model/mlp.py. 

Currently, `output/default` is set to output a 1-dimensional prediction (see [here](https://github.com/HazyResearch/spacetime/blob/7b7398caf3636d11dde4606eaeb96ea557aeee0e/configs/model/output/default.yaml), also copied)
```yaml
input_dim: 128
output_dim: 1
method: mlp
kwargs:
  input_dim: 128
  output_dim: 1
  activation: gelu
```
However, you'll want to change things such that the `self.layers` output in `mlp` matches in shape of `x`. 

```python
    def forward(self, x):
        x = self.layernorm(x)
        
        if self.input_shape == 'bdl':
            x = rearrange(x, 'b d l -> b l d')  # shape is now (b, l, 896) based on error message
        
        if self.skip_connection:
            # Layernorm with skip connection
            x = self.layers(x) + x    # self.layers(x) is still projecting down to (b, l, 128) however
        else: 
            x = self.layers(x)
```
when you used the `no_skip` config, that was not using the skip connection, hence it was not error'ing out because there was no additional `+ x`. It's just a linear projection output, so I wouldn't be surprised if the model also learned to forecast in this setup. However adjusting the `self.layers` `output_dim` s.t. you can use the skip connection may be beneficial.
